/*
 * File: app/view/MyContainer.js
 *
 * This file was generated by Sencha Architect version 3.0.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('jobby.view.MyContainer', {
    extend: 'Ext.Container',

    requires: [
        'Ext.Label',
        'Ext.Toolbar',
        'Ext.Button'
    ],

    config: {
        items: [
            {
                xtype: 'label',
                centered: true,
                html: 'Will this work?'
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                items: [
                    {
                        xtype: 'button',
                        text: 'MyButton'
                    }
                ]
            }
        ]
    }

});